version: "3.9"
services:
  # SOURCE : https://hub.docker.com/r/prestashop/prestashop/
  prestashop:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.prestashop
    image: prestashop/prestashop:latest
    restart: always
    container_name: prestashop
    networks:
      - prestashop
    extra_hosts:
      - "localdomain.local:host-gateway"
    hostname: prestashop
    expose:
      - "80"
    ports:
      - "8080:80"
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    volumes:
      #- ./:/var/www/html
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./override:/var/www/html/override
    environment:
      - PS_DEV_MODE=1
      - PS_INSTALL_AUTO=0
      - PS_LANGUAGE=fr
      - PS_COUNTRY=FR
      - PS_TIMEZONE=Europe/Paris
      - PS_SHOP_NAME=Pululuk
      - DB_NAME=prestashop
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=mycustompassword
      - PS_DOMAIN=localdomain.local
      - PS_FOLDER_ADMIN=admin123
      - ADMIN_MAIL=7tkt0qq4j@mozmail.com
      - ADMIN_PASSWD=password

  # SOURCE : https://hub.docker.com/_/mariadb
  mariadb:
    image: mariadb
    restart: always
    networks:
      - prestashop
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=prestashop
      - MYSQL_ROOT_PASSWORD=mycustompassword
  
  nginx:
    image: nginx:alpine
    restart: always
    networks:
      prestashop :
        aliases:
          - localdomain.local
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - prestashop

  # SOURCE : https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - prestashop
    links:
      - mariadb:mariadb
    ports:
      - 8081:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=mycustompassword

networks:
  prestashop:
    driver: bridge

volumes:
  db_data:
